import type { HolidayRule } from '../types'

/**
 * Vietnamese holidays as *rules*, never as fixed solar dates: everything on the
 * lunar calendar is resolved per year by the lunar module.
 */
export const VIETNAM_HOLIDAY_RULES: HolidayRule[] = [
  // ------------------------------- Solar -----------------------------------
  {
    kind: 'solar',
    id: 'vn-new-year',
    name: 'Tết Dương lịch',
    month: 1,
    day: 1,
    type: 'national',
    isPublicHoliday: true,
    description: 'Ngày đầu tiên của năm Dương lịch, người lao động được nghỉ 1 ngày.',
  },
  {
    kind: 'solar',
    id: 'vn-party-founding',
    name: 'Thành lập Đảng CSVN',
    month: 2,
    day: 3,
    type: 'observance',
  },
  {
    kind: 'solar',
    id: 'vn-women-day',
    name: 'Quốc tế Phụ nữ',
    month: 3,
    day: 8,
    type: 'international',
  },
  {
    kind: 'solar',
    id: 'vn-reunification',
    name: 'Ngày Giải phóng miền Nam',
    month: 4,
    day: 30,
    type: 'national',
    isPublicHoliday: true,
    description: 'Kỷ niệm ngày thống nhất đất nước 30/4/1975.',
  },
  {
    kind: 'solar',
    id: 'vn-labour-day',
    name: 'Ngày Quốc tế Lao động',
    month: 5,
    day: 1,
    type: 'national',
    isPublicHoliday: true,
  },
  {
    kind: 'solar',
    id: 'vn-uncle-ho-birthday',
    name: 'Sinh nhật Chủ tịch Hồ Chí Minh',
    month: 5,
    day: 19,
    type: 'observance',
  },
  {
    kind: 'solar',
    id: 'vn-children-day',
    name: 'Quốc tế Thiếu nhi',
    month: 6,
    day: 1,
    type: 'international',
  },
  {
    kind: 'solar',
    id: 'vn-war-invalids-day',
    name: 'Ngày Thương binh Liệt sĩ',
    month: 7,
    day: 27,
    type: 'observance',
  },
  {
    kind: 'solar',
    id: 'vn-national-day',
    name: 'Quốc khánh',
    month: 9,
    day: 2,
    type: 'national',
    isPublicHoliday: true,
    description: 'Kỷ niệm Tuyên ngôn Độc lập 2/9/1945. Người lao động được nghỉ 2 ngày.',
  },
  {
    kind: 'solar',
    id: 'vn-national-day-2',
    name: 'Nghỉ lễ Quốc khánh',
    month: 9,
    day: 1,
    type: 'national',
    isPublicHoliday: true,
  },
  {
    kind: 'solar',
    id: 'vn-women-day-vn',
    name: 'Ngày Phụ nữ Việt Nam',
    month: 10,
    day: 20,
    type: 'observance',
  },
  {
    kind: 'solar',
    id: 'vn-teachers-day',
    name: 'Ngày Nhà giáo Việt Nam',
    month: 11,
    day: 20,
    type: 'observance',
  },
  {
    kind: 'solar',
    id: 'vn-army-day',
    name: 'Ngày thành lập QĐND Việt Nam',
    month: 12,
    day: 22,
    type: 'observance',
  },

  // ------------------------------- Lunar -----------------------------------
  {
    kind: 'lunar',
    id: 'vn-tet-eve',
    name: 'Giao thừa (Tất niên)',
    lunarMonth: 12,
    lunarDay: 'last',
    type: 'lunar',
    isPublicHoliday: true,
    description: 'Ngày cuối cùng của năm Âm lịch.',
  },
  {
    kind: 'lunar',
    id: 'vn-tet-1',
    name: 'Tết Nguyên Đán',
    lunarMonth: 1,
    lunarDay: 1,
    type: 'lunar',
    isPublicHoliday: true,
    description: 'Mùng 1 Tết — ngày lễ lớn nhất trong năm, nghỉ 5 ngày.',
  },
  {
    kind: 'lunar',
    id: 'vn-tet-2',
    name: 'Mùng 2 Tết',
    lunarMonth: 1,
    lunarDay: 2,
    type: 'lunar',
    isPublicHoliday: true,
  },
  {
    kind: 'lunar',
    id: 'vn-tet-3',
    name: 'Mùng 3 Tết',
    lunarMonth: 1,
    lunarDay: 3,
    type: 'lunar',
    isPublicHoliday: true,
  },
  {
    kind: 'lunar',
    id: 'vn-tet-4',
    name: 'Mùng 4 Tết',
    lunarMonth: 1,
    lunarDay: 4,
    type: 'lunar',
    isPublicHoliday: true,
  },
  {
    kind: 'lunar',
    id: 'vn-ram-thang-gieng',
    name: 'Rằm tháng Giêng (Tết Nguyên Tiêu)',
    lunarMonth: 1,
    lunarDay: 15,
    type: 'lunar',
    description: 'Lễ Thượng Nguyên — "Lễ Phật quanh năm không bằng rằm tháng Giêng".',
  },
  {
    kind: 'lunar',
    id: 'vn-han-thuc',
    name: 'Tết Hàn Thực',
    lunarMonth: 3,
    lunarDay: 3,
    type: 'lunar',
    description: 'Ngày bánh trôi bánh chay.',
  },
  {
    kind: 'lunar',
    id: 'vn-hung-kings',
    name: 'Giỗ Tổ Hùng Vương',
    lunarMonth: 3,
    lunarDay: 10,
    type: 'lunar',
    isPublicHoliday: true,
    description: 'Ngày Quốc giỗ, người lao động được nghỉ 1 ngày.',
  },
  {
    kind: 'lunar',
    id: 'vn-phat-dan',
    name: 'Lễ Phật Đản',
    lunarMonth: 4,
    lunarDay: 15,
    type: 'lunar',
  },
  {
    kind: 'lunar',
    id: 'vn-doan-ngo',
    name: 'Tết Đoan Ngọ',
    lunarMonth: 5,
    lunarDay: 5,
    type: 'lunar',
    description: 'Tết diệt sâu bọ.',
  },
  {
    kind: 'lunar',
    id: 'vn-vu-lan',
    name: 'Lễ Vu Lan (Rằm tháng Bảy)',
    lunarMonth: 7,
    lunarDay: 15,
    type: 'lunar',
    description: 'Lễ báo hiếu cha mẹ, cũng là ngày xá tội vong nhân.',
  },
  {
    kind: 'lunar',
    id: 'vn-trung-thu',
    name: 'Tết Trung Thu',
    lunarMonth: 8,
    lunarDay: 15,
    type: 'lunar',
    description: 'Tết đoàn viên, tết thiếu nhi.',
  },
  {
    kind: 'lunar',
    id: 'vn-trung-cuu',
    name: 'Tết Trùng Cửu',
    lunarMonth: 9,
    lunarDay: 9,
    type: 'lunar',
  },
  {
    kind: 'lunar',
    id: 'vn-ong-cong-ong-tao',
    name: 'Ông Công Ông Táo',
    lunarMonth: 12,
    lunarDay: 23,
    type: 'lunar',
    description: 'Ngày tiễn Táo Quân về trời.',
  },
]
