/**
 * Autocomplete suggestions for the diary title input. Shown regardless of the current UI
 * language — Vietnamese and English entries both match, whichever the user is typing.
 */

const DIARY_TITLE_SUGGESTIONS_VI: string[] = [
  'Một ngày bình thường',
  'Hôm nay của tôi',
  'Chuyện của ngày hôm nay',
  'Một ngày đáng nhớ',
  'Ngày hôm nay có gì?',
  'Những điều xảy ra hôm nay',
  'Hôm nay thật khác',
  'Một ngày dài',
  'Một ngày nhẹ nhàng',
  'Một ngày bận rộn',
  'Một ngày thật vui',
  'Một ngày không như ý',
  'Một ngày đầy cảm xúc',
  'Một ngày nhiều suy nghĩ',
  'Một ngày thật đẹp',
  'Một ngày khó quên',
  'Một ngày đáng trân trọng',
  'Một ngày của riêng tôi',
  'Chậm lại một chút',
  'Khoảnh khắc hôm nay',
  'Chuyện nhỏ hôm nay',
  'Những điều nhỏ bé',
  'Một chút về hôm nay',
  'Ghi lại ngày hôm nay',
  'Nhật ký hôm nay',
  'Ngày mới bắt đầu',
  'Khởi đầu ngày mới',
  'Buổi sáng của tôi',
  'Chào ngày mới',
  'Sáng nay tôi nghĩ...',
  'Hôm nay tôi muốn...',
  'Kế hoạch cho hôm nay',
  'Điều tôi mong chờ hôm nay',
  'Điều quan trọng nhất hôm nay',
  'Mục tiêu của ngày hôm nay',
  'Hôm nay nhất định phải...',
  'Một ngày mới, một cơ hội mới',
  'Bắt đầu một ngày thật tốt',
  'Tâm trạng sáng nay',
  'Năng lượng hôm nay',
  'Cuối ngày',
  'Khép lại một ngày',
  'Tổng kết ngày hôm nay',
  'Nhìn lại ngày hôm nay',
  'Một ngày đã qua',
  'Trước khi đi ngủ',
  'Những suy nghĩ cuối ngày',
  'Hôm nay đã diễn ra thế nào?',
  'Hôm nay tôi đã làm được gì?',
  'Hôm nay tôi đã học được gì?',
  'Điều tuyệt vời nhất hôm nay',
  'Điều chưa tốt hôm nay',
  'Khoảnh khắc đáng nhớ nhất hôm nay',
  'Điều khiến tôi vui hôm nay',
  'Điều khiến tôi buồn hôm nay',
  'Điều khiến tôi bất ngờ hôm nay',
  'Một điều tôi muốn nhớ',
  'Hôm nay đáng nhớ vì...',
  'Nếu được sống lại ngày hôm nay',
  'Ngày mai sẽ tốt hơn',
  'Ngày mai tôi muốn...',
  'Chuẩn bị cho ngày mai',
  'Cảm xúc của tôi',
  'Tôi đang cảm thấy...',
  'Hôm nay lòng tôi...',
  'Một chút tâm trạng',
  'Những cảm xúc khó gọi tên',
  'Có một chút buồn',
  'Hôm nay tôi vui',
  'Một ngày nhiều niềm vui',
  'Một ngày hơi tệ',
  'Tôi ổn',
  'Tôi không ổn lắm',
  'Tôi cần một khoảng nghỉ',
  'Một ngày thật mệt',
  'Tôi đang lo lắng',
  'Tôi đang hạnh phúc',
  'Tôi đang bình yên',
  'Tôi đang mong chờ...',
  'Điều làm tôi tổn thương',
  'Điều khiến tôi mỉm cười',
  'Một niềm vui nhỏ',
  'Một chút cô đơn',
  'Những ngày như thế',
  'Chỉ muốn viết một chút',
  'Có những điều khó nói',
  'Những điều tôi giữ trong lòng',
  'Điều tôi chưa từng nói',
  'Tôi muốn nói rằng...',
  'Giá như...',
  'Có lẽ...',
  'Tôi tự hỏi...',
  'Tôi đang nghĩ về...',
  'Gần đây tôi thường nghĩ...',
  'Một suy nghĩ bất chợt',
  'Những suy nghĩ linh tinh',
  'Một phút suy ngẫm',
  'Điều tôi vừa nhận ra',
  'Hôm nay tôi nhận ra rằng...',
  'Có một điều tôi đã hiểu',
  'Một bài học cho bản thân',
  'Bài học hôm nay',
  'Điều cuộc sống dạy tôi',
  'Điều tôi cần thay đổi',
  'Điều tôi muốn cải thiện',
  'Tôi muốn trở thành...',
  'Phiên bản tốt hơn của tôi',
  'Tôi của hiện tại',
  'Tôi của ngày hôm qua',
  'Tôi của tương lai',
  'Gửi bản thân',
  'Gửi tôi của tương lai',
  'Gửi tôi của quá khứ',
  'Một lá thư cho chính mình',
  'Điều tôi muốn nhắc bản thân',
  'Đừng quên rằng...',
  'Hãy nhớ ngày hôm nay',
  'Một lời hứa với bản thân',
  'Tôi tự hào về mình vì...',
  'Tôi đã cố gắng',
  'Tôi đã làm tốt',
  'Tôi cần cố gắng hơn',
  'Một bước tiến nhỏ',
  'Tôi đang tiến về phía trước',
  'Chậm nhưng vẫn tiến',
  'Hành trình của tôi',
  'Một chương mới',
  'Khởi đầu mới',
  'Đã đến lúc thay đổi',
  'Một quyết định mới',
  'Quyết định của hôm nay',
  'Điều tôi muốn buông bỏ',
  'Học cách buông bỏ',
  'Những điều cần để lại phía sau',
  'Tôi muốn bắt đầu lại',
  'Ngày đầu tiên',
  'Một cột mốc mới',
  'Tôi đã thay đổi thế nào?',
  'Một năm trước tôi...',
  'Nhìn lại chính mình',
  'Tôi biết ơn hôm nay',
  'Những điều tôi biết ơn',
  'Ba điều đáng biết ơn',
  'Cảm ơn ngày hôm nay',
  'Một điều tốt đẹp',
  'Những điều làm cuộc sống đẹp hơn',
  'Hạnh phúc từ những điều nhỏ bé',
  'Điều đáng trân trọng',
  'Người tôi muốn cảm ơn',
  'Hôm nay thật may mắn',
  'Một khoảnh khắc hạnh phúc',
  'Điều làm tôi thấy đủ đầy',
  'Những điều đáng yêu hôm nay',
  'Một ngày đáng yêu',
  'Công việc hôm nay',
  'Nhật ký công việc',
  'Một ngày làm việc',
  'Hôm nay ở công ty',
  'Những việc đã hoàn thành',
  'Một ngày năng suất',
  'Hôm nay khá năng suất',
  'Hôm nay chẳng năng suất chút nào',
  'Điều tôi học được trong công việc',
  'Một vấn đề cần giải quyết',
  'Một ý tưởng mới',
  'Ý tưởng hôm nay',
  'Có thể thử cách này',
  'Một kế hoạch mới',
  'Dự án mới',
  'Tiến độ hôm nay',
  'Điều cần làm tiếp theo',
  'Một ngày nhiều deadline',
  'Cuối cùng cũng xong',
  'Tôi đã hoàn thành!',
  'Một thành tựu nhỏ',
  'Một chiến thắng nhỏ',
  'Học được điều mới',
  'Nhật ký học tập',
  'Hôm nay tôi học...',
  'Kiến thức mới hôm nay',
  'Một điều thú vị vừa học',
  'Điều tôi chưa hiểu',
  'Điều cần tìm hiểu thêm',
  'Ghi chú học tập hôm nay',
  'Hôm nay code gì?',
  'Nhật ký coding',
  'Bug của ngày hôm nay',
  'Cuối cùng cũng fix được',
  'Một bug khó chịu',
  'Một giải pháp hay',
  'Một đoạn code tôi thích',
  'Hôm nay tôi build...',
  'Điều mới trong lập trình',
  'Một công nghệ mới',
  'Một ý tưởng cho dự án',
  'Refactor hôm nay',
  'Một ngày debug',
  'Tại sao nó lại không chạy?',
  'À, hóa ra là vậy!',
  'Cuối cùng cũng hiểu',
  'Nhật ký tập luyện',
  'Buổi tập hôm nay',
  'Hôm nay tôi đã tập...',
  'Cảm giác sau buổi tập',
  'Tiến bộ hôm nay',
  'Một buổi tập tuyệt vời',
  'Một buổi tập thật mệt',
  'Hôm nay chạy bộ',
  'Hôm nay đi bộ',
  'Hôm nay nghỉ ngơi',
  'Chăm sóc bản thân',
  'Ngày dành cho bản thân',
  'Cơ thể tôi hôm nay',
  'Sức khỏe hôm nay',
  'Giấc ngủ tối qua',
  'Tôi cần nghỉ ngơi',
  'Một ngày hồi phục',
  'Hôm nay ăn gì?',
  'Một bữa ăn đáng nhớ',
  'Nhật ký du lịch',
  'Chuyến đi của tôi',
  'Ngày đầu của chuyến đi',
  'Ngày cuối của chuyến đi',
  'Hôm nay tôi đã đến...',
  'Một nơi mới',
  'Một thành phố mới',
  'Một chuyến đi đáng nhớ',
  'Một chuyến đi bất ngờ',
  'Một cuộc phiêu lưu nhỏ',
  'Đi đâu đó thật xa',
  'Lạc giữa một nơi xa lạ',
  'Một nơi tôi muốn quay lại',
  'Nơi đẹp nhất hôm nay',
  'Một góc thành phố',
  'Hoàng hôn hôm nay',
  'Bình minh hôm nay',
  'Một buổi chiều đẹp',
  'Một đêm đáng nhớ',
  'Những người tôi gặp',
  'Một người đặc biệt',
  'Cuộc gặp hôm nay',
  'Một cuộc trò chuyện đáng nhớ',
  'Chuyện của chúng ta',
  'Hôm nay chúng ta...',
  'Một ngày bên nhau',
  'Khoảnh khắc bên nhau',
  'Điều tôi muốn nói với bạn',
  'Có người làm tôi vui',
  'Tôi nhớ một người',
  'Nhớ...',
  'Gặp lại',
  'Một cuộc gặp bất ngờ',
  'Một lời nói khiến tôi nhớ mãi',
  'Một người tôi biết ơn',
  'Gia đình hôm nay',
  'Một ngày bên gia đình',
  'Bữa cơm gia đình',
  'Chuyện nhà',
  'Một khoảnh khắc cùng gia đình',
  'Một ngày với bạn bè',
  'Hội bạn hôm nay',
  'Cuộc vui hôm nay',
  'Lâu rồi mới gặp',
  'Chuyện tình cảm',
  'Tôi và tình yêu',
  'Hôm nay trái tim tôi...',
  'Một chút rung động',
  'Tôi thích một người',
  'Có lẽ tôi đang yêu',
  'Một ngày của chúng ta',
  'Một kỷ niệm của chúng ta',
  'Điều tôi yêu ở bạn',
  'Điều tôi muốn nói nhưng chưa nói',
  'Một ngày đặc biệt',
  'Kỷ niệm hôm nay',
  'Chuyện cũ',
  'Ngày ấy',
  'Tôi vẫn còn nhớ',
  'Một ký ức bất chợt',
  'Những ngày đã qua',
  'Một người trong ký ức',
  'Một nơi trong ký ức',
  'Một bài hát và một ký ức',
  'Một bức ảnh, một câu chuyện',
  'Chuyện của ngày xưa',
  'Nếu ngày đó...',
  'Thời gian trôi nhanh thật',
  'Lại thêm một tuổi',
  'Sinh nhật của tôi',
  'Một tuổi mới',
  'Năm mới',
  'Ngày đầu năm',
  'Ngày cuối năm',
  'Nhìn lại một năm',
  'Một năm của tôi',
  'Những điều tuyệt vời trong năm',
  'Những điều tôi đã đạt được',
  'Những điều tôi bỏ lỡ',
  'Điều tôi muốn làm trong năm tới',
  'Mục tiêu mới',
  'Mục tiêu tháng này',
  'Mục tiêu tuần này',
  'Mục tiêu hôm nay',
  'Kế hoạch tuần mới',
  'Kế hoạch tháng mới',
  'Tháng này của tôi',
  'Một tháng đã qua',
  'Tổng kết tuần',
  'Tổng kết tháng',
  'Tổng kết năm',
  'Tuần này thế nào?',
  'Tháng này thế nào?',
  'Dạo này thế nào?',
  'Dạo này tôi...',
  'Cuộc sống gần đây',
  'Một chút cập nhật',
  'Những ngày gần đây',
  'Tôi đang sống thế nào?',
  'Điều tôi đang theo đuổi',
  'Điều tôi thực sự muốn',
  'Ước mơ của tôi',
  'Một giấc mơ mới',
  'Danh sách những điều muốn làm',
  'Nơi tôi muốn đến',
  'Người tôi muốn trở thành',
  'Cuộc sống tôi mong muốn',
  '5 năm nữa tôi sẽ...',
  'Một ngày trong tương lai',
  'Khi mọi thứ tốt hơn',
  'Tôi tin rằng...',
  'Tôi hy vọng...',
  'Mong rằng...',
  'Rồi mọi chuyện sẽ ổn',
  'Mọi thứ rồi sẽ qua',
  'Ngày mai là một ngày mới',
  'Hãy cứ tiếp tục',
  'Không sao, thử lại',
  'Bắt đầu lại từ đây',
  'Hôm nay là đủ',
  'Chỉ cần tốt hơn hôm qua',
  'Từng chút một',
  'Một bước mỗi ngày',
  'Cứ đi rồi sẽ đến',
  'Tôi chọn bình yên',
  'Học cách yêu bản thân',
  'Học cách sống chậm',
  'Học cách chấp nhận',
  'Học cách trưởng thành',
  'Trưởng thành là...',
  'Cuộc sống là...',
  'Hạnh phúc là...',
  'Thành công với tôi là...',
  'Điều quan trọng với tôi',
  'Tôi thực sự cần gì?',
  'Điều gì khiến tôi hạnh phúc?',
  'Tôi đang chạy theo điều gì?',
  'Tôi muốn sống như thế nào?',
  'Nếu hôm nay là ngày cuối...',
  'Nếu tôi có thể quay lại...',
  'Nếu tôi không sợ...',
  'Nếu mọi thứ đều có thể...',
  'Một câu hỏi cho bản thân',
  'Một câu trả lời cho chính mình',
  'Không cần tiêu đề',
  'Chỉ là vài dòng',
  'Viết cho nhẹ lòng',
  'Viết để nhớ',
  'Viết để không quên',
  'Viết vì muốn viết',
  'Chuyện không đầu không cuối',
  'Một chút linh tinh',
  'Linh tinh hôm nay',
  'Chẳng biết viết gì',
  'Không biết bắt đầu từ đâu',
  'Có quá nhiều điều muốn nói',
  'Một ngày như bao ngày',
  'Và thế là hết một ngày',
  'Hôm nay, thế thôi.',
  'Ngày này, tháng này, năm này',
  'Lưu lại khoảnh khắc này',
  'Để sau này đọc lại',
  'Mong tôi của tương lai sẽ đọc được',
  'Đây là cuộc sống của tôi',
  'Một trang nhật ký mới',
  'Trang tiếp theo',
  'Câu chuyện vẫn tiếp tục',
  'To be continued...',
]

const DIARY_TITLE_SUGGESTIONS_EN: string[] = [
  'A normal day',
  'My today',
  "Today's story",
  'A day to remember',
  'What happened today?',
  'Things that happened today',
  'Today feels different',
  'A long day',
  'A gentle day',
  'A busy day',
  'A really fun day',
  "A day that didn't go as planned",
  'An emotional day',
  'A day full of thoughts',
  'A beautiful day',
  'An unforgettable day',
  'A day worth cherishing',
  'A day of my own',
  'Slowing down a little',
  'This moment today',
  'A small thing today',
  'The little things',
  'A little about today',
  'Recording today',
  "Today's diary",
  'A new day begins',
  'The start of a new day',
  'My morning',
  'Hello, new day',
  'This morning I thought...',
  'Today I want...',
  'Plan for today',
  "What I'm looking forward to today",
  'The most important thing today',
  "Today's goal",
  'Today I must...',
  'A new day, a new chance',
  'Starting a great day',
  "This morning's mood",
  "Today's energy",
  'End of day',
  'Closing out the day',
  'Wrapping up today',
  'Looking back on today',
  'A day gone by',
  'Before bed',
  'End-of-day thoughts',
  'How did today go?',
  'What did I get done today?',
  'What did I learn today?',
  'The best thing about today',
  "What wasn't so great today",
  'The most memorable moment today',
  'What made me happy today',
  'What made me sad today',
  'What surprised me today',
  'Something I want to remember',
  'Today is memorable because...',
  'If I could relive today',
  'Tomorrow will be better',
  'Tomorrow I want...',
  'Getting ready for tomorrow',
  'My feelings',
  "I'm feeling...",
  'My heart today...',
  'A little mood check',
  'Feelings hard to name',
  'A little bit sad',
  "I'm happy today",
  'A day full of joy',
  'A bit of a rough day',
  "I'm okay",
  "I'm not doing great",
  'I need a break',
  'A really tiring day',
  "I'm feeling anxious",
  "I'm feeling happy",
  "I'm feeling at peace",
  "I'm looking forward to...",
  'What hurt me',
  'What made me smile',
  'A small joy',
  'A little lonely',
  'Days like this',
  'Just want to write a little',
  "Some things are hard to say",
  'Things I keep to myself',
  "Something I've never said",
  'I want to say that...',
  'If only...',
  'Maybe...',
  'I wonder...',
  "I'm thinking about...",
  'Lately I keep thinking...',
  'A random thought',
  'Random thoughts',
  'A moment of reflection',
  'Something I just realized',
  'Today I realized that...',
  'There is something I finally understood',
  'A lesson for myself',
  "Today's lesson",
  'What life is teaching me',
  'Something I need to change',
  'Something I want to improve',
  'I want to become...',
  'A better version of me',
  'The me right now',
  "Yesterday's me",
  'My future self',
  'To myself',
  'To my future self',
  'To my past self',
  'A letter to myself',
  'Something I want to remind myself',
  "Don't forget that...",
  'Remember this day',
  'A promise to myself',
  "I'm proud of myself for...",
  'I tried',
  'I did well',
  'I need to try harder',
  'A small step forward',
  "I'm moving forward",
  'Slow but still moving',
  'My journey',
  'A new chapter',
  'A fresh start',
  'Time for a change',
  'A new decision',
  "Today's decision",
  'Something I want to let go of',
  'Learning to let go',
  'Things to leave behind',
  'I want to start over',
  'Day one',
  'A new milestone',
  'How have I changed?',
  'A year ago, I...',
  'Looking back at myself',
  'Grateful today',
  "Things I'm grateful for",
  "Three things I'm grateful for",
  'Thankful for today',
  'One good thing',
  'Things that make life better',
  'Happiness in the little things',
  'Something worth cherishing',
  'Someone I want to thank',
  'Today felt lucky',
  'A happy moment',
  'What makes me feel fulfilled',
  'Lovely things about today',
  'A lovely day',
  'Work today',
  'Work diary',
  'A day at work',
  'At the office today',
  'Things I got done',
  'A productive day',
  'Pretty productive today',
  'Not productive at all today',
  'What I learned at work',
  'A problem to solve',
  'A new idea',
  "Today's idea",
  'Maybe try this approach',
  'A new plan',
  'A new project',
  "Today's progress",
  'What to do next',
  'A day full of deadlines',
  'Finally done',
  'I finished it!',
  'A small achievement',
  'A small win',
  'Learned something new',
  'Learning journal',
  'Today I learned...',
  'New knowledge today',
  'Something interesting I just learned',
  "Something I don't understand yet",
  'Something to look into further',
  "Today's study notes",
  'What did I code today?',
  'Coding diary',
  "Today's bug",
  'Finally fixed it',
  'An annoying bug',
  'A nice solution',
  'A piece of code I like',
  "Today I'm building...",
  'Something new in programming',
  'A new technology',
  'An idea for the project',
  'Refactoring today',
  'A day of debugging',
  "Why isn't this working?",
  "Ah, so that's why!",
  'Finally understood it',
  'Workout journal',
  "Today's workout",
  'Today I trained...',
  'How I felt after the workout',
  "Today's progress",
  'A great workout',
  'A really tiring workout',
  'Went for a run today',
  'Went for a walk today',
  'Resting today',
  'Taking care of myself',
  'A day for myself',
  'My body today',
  'Health today',
  "Last night's sleep",
  'I need to rest',
  'A recovery day',
  'What did I eat today?',
  'A memorable meal',
  'Travel journal',
  'My trip',
  'First day of the trip',
  'Last day of the trip',
  'Today I went to...',
  'A new place',
  'A new city',
  'A trip to remember',
  'An unexpected trip',
  'A small adventure',
  'Going somewhere far',
  'Lost in an unfamiliar place',
  'A place I want to revisit',
  'The best place today',
  'A corner of the city',
  "Today's sunset",
  "Today's sunrise",
  'A beautiful afternoon',
  'A night to remember',
  'People I met',
  'Someone special',
  "Today's meeting",
  'A conversation to remember',
  'Our story',
  'Today we...',
  'A day together',
  'A moment together',
  'Something I want to tell you',
  'Someone made me happy',
  'I miss someone',
  'Missing...',
  'Meeting again',
  'An unexpected meeting',
  "Something said that I'll never forget",
  "Someone I'm grateful for",
  'Family today',
  'A day with family',
  'Family dinner',
  'Home stuff',
  'A moment with family',
  'A day with friends',
  'Hanging out with friends today',
  'Fun times today',
  "It's been a while since we met",
  'Matters of the heart',
  'Me and love',
  'My heart today...',
  'A little flutter',
  'I like someone',
  "Maybe I'm falling in love",
  "A day that's ours",
  'A memory of ours',
  'What I love about you',
  "Something I want to say but haven't",
  'A special day',
  "Today's memory",
  'An old story',
  'Back then',
  'I still remember',
  'A sudden memory',
  'Days gone by',
  'Someone in my memory',
  'A place in my memory',
  'A song and a memory',
  'A photo, a story',
  'A story from the past',
  'If only that day...',
  'Time really flies',
  'Another year older',
  'My birthday',
  'A new year older',
  'New year',
  'The first day of the year',
  'The last day of the year',
  'Looking back on a year',
  'My year',
  'Great things this year',
  "Things I've achieved",
  'Things I missed out on',
  'Something I want to do next year',
  'A new goal',
  "This month's goal",
  "This week's goal",
  "Today's goal",
  "New week's plan",
  "New month's plan",
  'My month',
  'A month gone by',
  'Weekly wrap-up',
  'Monthly wrap-up',
  'Yearly wrap-up',
  'How was this week?',
  'How was this month?',
  'How have things been lately?',
  "Lately, I've been...",
  'Life lately',
  'A little update',
  'Recent days',
  'How am I living right now?',
  "What I'm chasing",
  'What I really want',
  'My dream',
  'A new dream',
  'A list of things to do',
  'A place I want to go',
  'The person I want to become',
  'The life I want',
  'In 5 years, I will...',
  'A day in the future',
  'When things get better',
  'I believe that...',
  'I hope...',
  'I wish...',
  'Everything will be fine',
  'Everything passes eventually',
  'Tomorrow is a new day',
  'Just keep going',
  "It's okay, try again",
  'Starting over from here',
  'Today is enough',
  'Just better than yesterday',
  'One step at a time',
  'A step every day',
  "Keep going and you'll get there",
  'I choose peace',
  'Learning to love myself',
  'Learning to slow down',
  'Learning to accept',
  'Learning to grow',
  'Growing up means...',
  'Life is...',
  'Happiness is...',
  'Success, to me, is...',
  'What matters to me',
  'What do I really need?',
  'What makes me happy?',
  'What am I chasing?',
  'How do I want to live?',
  'If today were the last day...',
  'If I could go back...',
  "If I weren't afraid...",
  'If anything were possible...',
  'A question for myself',
  'An answer for myself',
  'No title needed',
  'Just a few lines',
  'Writing to feel lighter',
  'Writing to remember',
  "Writing so I don't forget",
  'Writing because I want to',
  'A story with no beginning or end',
  'A bit of randomness',
  'Random thoughts today',
  "Don't know what to write",
  "Don't know where to start",
  'So much I want to say',
  'A day like any other',
  "And that's another day done",
  "Today, that's it.",
  'This day, this month, this year',
  'Saving this moment',
  'To read again later',
  'Hoping my future self will read this',
  'This is my life',
  'A new diary page',
  'The next page',
  'The story continues',
  'To be continued...',
]

/** Combined pool used for the title autocomplete — both languages match regardless of UI locale. */
export const DIARY_TITLE_SUGGESTIONS: string[] = [...DIARY_TITLE_SUGGESTIONS_VI, ...DIARY_TITLE_SUGGESTIONS_EN]
